---
# This playbook deploys a kubernetes cluster
# with the default addons.

- hosts: all
  gather_facts: false
  become: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- include: deploy-etcd.yml

# Install docker
- include: deploy-docker.yml

# install flannel
- include: deploy-flannel.yml

# install kube master services
- include: deploy-master.yml

# launch addons, like dns
- include: deploy-addons.yml

# install kubernetes on the nodes
- include: deploy-node.yml
